language:
- node_js
node_js:
- "10.13"
sudo: false
before_install:
- export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
install:
- yarn
script:
- yarn code_coverage
- yarn coveralls
after_success:
- export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
- export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
- export CI_BRANCH="$TRAVIS_BRANCH"